{
# 公众号配置
# 公众号appId
"app_id": "wxacf7b497284e047a",
# 公众号appSecret
"app_secret": "848d48c91b16081d53a58fd001dd8ca1",
# 模板消息id
"template_id": "guMtIu2jubNMpvvkmBeUeGiwOttar3x3E7E2mRmFYiA",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["oZ12d6a0uFA7zlDQm-_82hiS-MzU"],

# 信息配置
# 所在省份
"province": "山西",
# 所在城市
"city": "太原",
# 生日1
"birthday1": "2003-8-12",
# 生日2
"birthday2": "2002-11-20",
# 生日3
"birthday3": "1997-01-03",
# 在一起的日子，格式同上
"love_date": "2020-01-01"
}
